version: "3.6"
services:
  prometheus:
    image: appliedblockchain/mantle-prometheus:latest
    build:
      context: .
      dockerfile: ./monitoring/prometheus/Dockerfile
    volumes:
      - prometheus-data:/prometheus
    ports:
      - '9090:9090'
  grafana:
    image: appliedblockchain/mantle-grafana:latest
    build:
      context: .
      dockerfile: ./monitoring/grafana/Dockerfile
    depends_on:
      - prometheus
    networks:
      - main
    ports:
      - '9080:3000'
volumes:
  prometheus-data:
