FROM node:10.13-alpine

RUN apk add --update --no-cache alpine-sdk git python && \
  rm -rf /tmp/* /var/cache/apk/*

USER node

RUN mkdir /home/node/react
WORKDIR /home/node/react

COPY package.json package.json

ARG NPM_TOKEN

RUN echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc &&\
  npm i &&\
  rm ~/.npmrc

COPY . /home/node/react/

RUN npm run build

FROM nginx:alpine
COPY --from=builder /home/node/react/build /usr/share/nginx/html
COPY ./docker/nginx-dev.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
