FROM node:latest

RUN mkdir /app
WORKDIR /app

ARG NPM_TOKEN
RUN echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

ENV PATH /app/node_modules/.bin:$PATH

COPY . /app

RUN npm i
RUN npm install react-scripts -g --silent

EXPOSE 80
RUN . src/contracts/exportAddresses.sh
RUN react-app-rewired start
