[parity]
chain = "/parity/chain.json"

[account]
password = ["/parity/password"]
unlock = ["0x0fe32bb59e5993e6b5d45a963204aaffea2379c9"]

[network]
reserved_peers = "/parity/reserved_peers"
nat = "none"
reserved_only = true
discovery = false

[ui]
interface = "0.0.0.0"

[rpc]
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "personal", "parity_accounts", "signer", "parity_set"]

[mining]
reseal_on_txs = "none"
engine_signer = "0x0fe32bb59e5993e6b5d45a963204aaffea2379c9"
reseal_min_period = 10
reseal_max_period = 10000
usd_per_tx = "0"
tx_gas_limit = "50000000"

[websockets]
disable = false
port = 8546
interface = "all"
origins = ["all"]
apis = ["all"]
hosts = ["all"]
