version: '3'

services:
  react:
    build:
      context: ../react
      dockerfile: Dockerfile-dev
      args:
        - NPM_TOKEN
    volumes:
      - ../react/src/:/home/node/react/src
    ports:
      - 3000:3000
  api:
    build:
      context: ../api
      dockerfile: Dockerfile-dev
      args:
        - NPM_TOKEN
    volumes:
      - ../api/src/:/home/node/api/src
      - ../api/config/:/home/node/api/config
      - ../api/contracts/:/home/node/api/contracts
    environment:
      NODE_ENV: development
      ETHEREUM_JSONRPC_ENDPOINT: http://parity:8545
      CONTRACT_ADDRESS: "$CONTRACT_ADDRESS"
      ELASTICSEARCH: elasticsearch
    networks:
      - main
    ports:
      - 8080:8080
    depends_on:
      - parity
      - redis
      - elasticsearch
  parity:
    image: appliedblockchain/parity-solo-instant:latest
    entrypoint: ["/parity/parity", "--config", "/solo/node.toml", "--unsafe-expose", "--gasprice", "1"]
    restart: always
    volumes:
      - parity:/solo/chains
    ports:
      - 8545:8545
      - 8546:8546
    networks:
      - main
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - main
volumes:
  parity:
  elasticsearch:
networks:
  main: