FROM parity/parity:v1.11.8

ARG NPM_TOKEN
RUN echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

RUN mkdir -p /parity

WORKDIR /parity

COPY ./parity/chain/spec.json      spec.json
COPY ./parity/chain/reserved_peers reserved_peers

ARG PARITY_ID
RUN echo ${PARITY_ID}

COPY ./parity/${PARITY_ID}/password       password
COPY ./parity/${PARITY_ID}/authority.toml authority.toml
COPY ./parity/${PARITY_ID}/parity         ./data/keys/parity
COPY ./parity/${PARITY_ID}/network.key    ./data/network/key

RUN apt-get update
RUN apt-get install curl bash
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install nodejs -y && \
  rm -rf /tmp/*

COPY ./package* /parity/
COPY ./docker/entrypoint.sh entrypoint.sh
RUN npm install

ENTRYPOINT [ "sh", "./entrypoint.sh" ]

