FROM parity/parity:v1.11.8

RUN mkdir -p /parity

WORKDIR /parity

COPY ./parity/chain/spec.json      spec.json
COPY ./parity/chain/reserved_peers reserved_peers

ARG PARITY_ID
RUN echo ${PARITY_ID}

COPY ./parity/${PARITY_ID}/password       password
COPY ./parity/${PARITY_ID}/authority.toml authority.toml
COPY ./parity/${PARITY_ID}/parity         ./data/keys/parity
COPY ./parity/${PARITY_ID}/network.key    ./data/network/key
