version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9

    working_directory: ~/workspace

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Authorize NPM
          command: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install solidity
          command: wget https://github.com/ethereum/solidity/releases/download/v0.4.23/solc-static-linux && chmod +x solc-static-linux && sudo mv solc-static-linux /usr/bin/solc

      - run:
          name: Eslint
          command: npm run lint

      - run:
          name: Unit tests
          command: npm run test:ci

      - run:
          name: Compile
          command: solc --combined-json abi,bin contracts/Store.sol > Store.json

      - persist_to_workspace:
          root: .
          paths:
            - Store.json

  publish_npm_on_tag:
    docker:
      - image: circleci/node:9

    working_directory: ~/workspace

    steps:
      - checkout

      - run:
          name: Authorize NPM
          command: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc

      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}

      - run: npm i

      - attach_workspace:
          at: /tmp/artefacts

      - run:
          name: Publish to NPM
          command: |
            npm publish
            npm run publish:artefacts /tmp/artefacts/Store.json store-contract

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              only: /v.*/
      - publish_npm_on_tag:
          context: org-global
          requires:
            - build
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
