FROM node:latest

RUN mkdir /app
WORKDIR /app

ARG NPM_TOKEN
RUN echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

COPY . /app
RUN npm i

EXPOSE 3000

RUN ls
RUN . contracts/exportAddresses.sh
RUN node ./run
